# -------------------------------------
# Makefile; AL2020 (v1.25)             
# (c)2020 The Open University of Japan 
# -------------------------------------

# CC = cc
# CC = clang
CC = gcc
CFLAGS = -Wall -O2
LIBS = -lm

all: ex12-1 ex12-2 ex12-3 ex12-4 ex12-5 q12-1 q12-2 

ex12-1: ex12-1.c
	$(CC) ex12-1.c $(CFLAGS) $(LIBS) -o ex12-1

ex12-2: ex12-2.c
	$(CC) ex12-2.c $(CFLAGS) $(LIBS) -o ex12-2

ex12-3: ex12-3.c
	$(CC) ex12-3.c $(CFLAGS) $(LIBS) -o ex12-3

ex12-4: ex12-4.c
	$(CC) ex12-4.c $(CFLAGS) $(LIBS) -o ex12-4

ex12-5: ex12-5.c
	$(CC) ex12-5.c $(CFLAGS) $(LIBS) -o ex12-5

q12-1: q12-1.c
	$(CC) q12-1.c $(CFLAGS) $(LIBS) -o q12-1

q12-2: q12-2.c
	$(CC) q12-2.c $(CFLAGS) $(LIBS) -o q12-2

clean:
	rm -rf *~  ex12-1 ex12-2 ex12-3 ex12-4 ex12-5 q12-1 q12-2 

