# -------------------------------------
# Makefile; AL2020 (v1.00)             
# (c)2020 The Open University of Japan 
# -------------------------------------

# CC = cc
# CC = clang
CC = gcc
CFLAGS = -Wall -Wno-unused-result -O2 
LIBS = -lm

all: ex1-1 ex1-2 ex1-3 ex1-4 ex1-5 ex1-6 ex1-7 q1-1 q1-2 q1-3 

ex1-1: ex1-1.c
	$(CC) $(CFLAGS) ex1-1.c -o ex1-1 $(LIBS)

ex1-2: ex1-2.c
	$(CC) $(CFLAGS) ex1-2.c -o ex1-2 $(LIBS)

ex1-3: ex1-3.c
	$(CC) $(CFLAGS) ex1-3.c -o ex1-3 $(LIBS)

ex1-4: ex1-4.c
	$(CC) $(CFLAGS) ex1-4.c -o ex1-4 $(LIBS)

ex1-5: ex1-5.c
	$(CC) $(CFLAGS) ex1-5.c -o ex1-5 $(LIBS)

ex1-6: ex1-6.c
	$(CC) $(CFLAGS) ex1-6.c -o ex1-6 $(LIBS)

ex1-7: ex1-7.c
	$(CC) $(CFLAGS) ex1-7.c -o ex1-7 $(LIBS)

q1-1: q1-1.c
	$(CC) $(CFLAGS) q1-1.c -o q1-1 $(LIBS)

q1-2: q1-2.c
	$(CC) $(CFLAGS) q1-2.c -o q1-2 $(LIBS)

q1-3: q1-3.c
	$(CC) $(CFLAGS) q1-3.c -o q1-3 $(LIBS)

clean:
	rm -rf *~  ex1-1 ex1-2 ex1-3 ex1-4 ex1-5 ex1-6 ex1-7 q1-1 q1-2 q1-3 

