# -------------------------------------
# Makefile; AL2020 (v1.25)             
# (c)2020 The Open University of Japan 
# -------------------------------------

# CC = cc
# CC = clang
CC = gcc
CFLAGS = -Wall -O2
LIBS = -lm

all: ex3-1 ex3-10 ex3-11 ex3-2 ex3-3 ex3-4 ex3-5 ex3-6 ex3-7 ex3-8 ex3-9 q3-1 q3-2 q3-3 q3-4 q3-5 

ex3-1: ex3-1.c
	$(CC) ex3-1.c $(CFLAGS) $(LIBS) -o ex3-1

ex3-10: ex3-10.c
	$(CC) ex3-10.c $(CFLAGS) $(LIBS) -o ex3-10

ex3-11: ex3-11.c
	$(CC) ex3-11.c $(CFLAGS) $(LIBS) -o ex3-11

ex3-2: ex3-2.c
	$(CC) ex3-2.c $(CFLAGS) $(LIBS) -o ex3-2

ex3-3: ex3-3.c
	$(CC) ex3-3.c $(CFLAGS) $(LIBS) -o ex3-3

ex3-4: ex3-4.c
	$(CC) ex3-4.c $(CFLAGS) $(LIBS) -o ex3-4

ex3-5: ex3-5.c
	$(CC) ex3-5.c $(CFLAGS) $(LIBS) -o ex3-5

ex3-6: ex3-6.c
	$(CC) ex3-6.c $(CFLAGS) $(LIBS) -o ex3-6

ex3-7: ex3-7.c
	$(CC) ex3-7.c $(CFLAGS) $(LIBS) -o ex3-7

ex3-8: ex3-8.c
	$(CC) ex3-8.c $(CFLAGS) $(LIBS) -o ex3-8

ex3-9: ex3-9.c
	$(CC) ex3-9.c $(CFLAGS) $(LIBS) -o ex3-9

q3-1: q3-1.c
	$(CC) q3-1.c $(CFLAGS) $(LIBS) -o q3-1

q3-2: q3-2.c
	$(CC) q3-2.c $(CFLAGS) $(LIBS) -o q3-2

q3-3: q3-3.c
	$(CC) q3-3.c $(CFLAGS) $(LIBS) -o q3-3

q3-4: q3-4.c
	$(CC) q3-4.c $(CFLAGS) $(LIBS) -o q3-4

q3-5: q3-5.c
	$(CC) q3-5.c $(CFLAGS) $(LIBS) -o q3-5

clean:
	rm -rf *~  ex3-1 ex3-10 ex3-11 ex3-2 ex3-3 ex3-4 ex3-5 ex3-6 ex3-7 ex3-8 ex3-9 q3-1 q3-2 q3-3 q3-4 q3-5 

