# -------------------------------------
# Makefile; AL2020 (v1.00)             
# (c)2020 The Open University of Japan 
# -------------------------------------

# CC = cc
# CC = clang
CC = gcc
CFLAGS = -Wall -Wno-unused-result -O2 
LIBS = -lm

all: ex6-1 ex6-10 ex6-2 ex6-3 ex6-4 ex6-5 ex6-6 ex6-7 ex6-8 ex6-9 q6-1 q6-2 q6-3 q6-4 q6-5 q6-6 

ex6-1: ex6-1.c
	$(CC) $(CFLAGS) ex6-1.c -o ex6-1 $(LIBS)

ex6-10: ex6-10.c
	$(CC) $(CFLAGS) ex6-10.c -o ex6-10 $(LIBS)

ex6-2: ex6-2.c
	$(CC) $(CFLAGS) ex6-2.c -o ex6-2 $(LIBS)

ex6-3: ex6-3.c
	$(CC) $(CFLAGS) ex6-3.c -o ex6-3 $(LIBS)

ex6-4: ex6-4.c
	$(CC) $(CFLAGS) ex6-4.c -o ex6-4 $(LIBS)

ex6-5: ex6-5.c
	$(CC) $(CFLAGS) ex6-5.c -o ex6-5 $(LIBS)

ex6-6: ex6-6.c
	$(CC) $(CFLAGS) ex6-6.c -o ex6-6 $(LIBS)

ex6-7: ex6-7.c
	$(CC) $(CFLAGS) ex6-7.c -o ex6-7 $(LIBS)

ex6-8: ex6-8.c
	$(CC) $(CFLAGS) ex6-8.c -o ex6-8 $(LIBS)

ex6-9: ex6-9.c
	$(CC) $(CFLAGS) ex6-9.c -o ex6-9 $(LIBS)

q6-1: q6-1.c
	$(CC) $(CFLAGS) q6-1.c -o q6-1 $(LIBS)

q6-2: q6-2.c
	$(CC) $(CFLAGS) q6-2.c -o q6-2 $(LIBS)

q6-3: q6-3.c
	$(CC) $(CFLAGS) q6-3.c -o q6-3 $(LIBS)

q6-4: q6-4.c
	$(CC) $(CFLAGS) q6-4.c -o q6-4 $(LIBS)

q6-5: q6-5.c
	$(CC) $(CFLAGS) q6-5.c -o q6-5 $(LIBS)

q6-6: q6-6.c
	$(CC) $(CFLAGS) q6-6.c -o q6-6 $(LIBS)

clean:
	rm -rf *~  ex6-1 ex6-10 ex6-2 ex6-3 ex6-4 ex6-5 ex6-6 ex6-7 ex6-8 ex6-9 q6-1 q6-2 q6-3 q6-4 q6-5 q6-6 

