# -------------------------------------
# Makefile; AL2020 (v1.25)             
# (c)2020 The Open University of Japan 
# -------------------------------------

# CC = cc
# CC = clang
CC = gcc
CFLAGS = -Wall -O2
LIBS = -lm

all: ex10-1 ex10-2 ex10-3 ex10-4 ex10-5 q10-1 q10-2 q10-3 

ex10-1: ex10-1.c
	$(CC) ex10-1.c $(CFLAGS) $(LIBS) -o ex10-1

ex10-2: ex10-2.c
	$(CC) ex10-2.c $(CFLAGS) $(LIBS) -o ex10-2

ex10-3: ex10-3.c
	$(CC) ex10-3.c $(CFLAGS) $(LIBS) -o ex10-3

ex10-4: ex10-4.c
	$(CC) ex10-4.c $(CFLAGS) $(LIBS) -o ex10-4

ex10-5: ex10-5.c
	$(CC) ex10-5.c $(CFLAGS) $(LIBS) -o ex10-5

q10-1: q10-1.c
	$(CC) q10-1.c $(CFLAGS) $(LIBS) -o q10-1

q10-2: q10-2.c
	$(CC) q10-2.c $(CFLAGS) $(LIBS) -o q10-2

q10-3: q10-3.c
	$(CC) q10-3.c $(CFLAGS) $(LIBS) -o q10-3

clean:
	rm -rf *~  ex10-1 ex10-2 ex10-3 ex10-4 ex10-5 q10-1 q10-2 q10-3 

