# -------------------------------------
# Makefile; AL2020 (v1.00)             
# (c)2020 The Open University of Japan 
# -------------------------------------

# CC = cc
# CC = clang
CC = gcc
CFLAGS = -Wall -Wno-unused-result -O2 
LIBS = -lm

all: ex5-1 ex5-2 ex5-3 ex5-4 ex5-5 ex5-6 ex5-7 q5-1 q5-2 q5-3 q5-4 q5-5 

ex5-1: ex5-1.c
	$(CC) $(CFLAGS) ex5-1.c -o ex5-1 $(LIBS)

ex5-2: ex5-2.c
	$(CC) $(CFLAGS) ex5-2.c -o ex5-2 $(LIBS)

ex5-3: ex5-3.c
	$(CC) $(CFLAGS) ex5-3.c -o ex5-3 $(LIBS)

ex5-4: ex5-4.c
	$(CC) $(CFLAGS) ex5-4.c -o ex5-4 $(LIBS)

ex5-5: ex5-5.c
	$(CC) $(CFLAGS) ex5-5.c -o ex5-5 $(LIBS)

ex5-6: ex5-6.c
	$(CC) $(CFLAGS) ex5-6.c -o ex5-6 $(LIBS)

ex5-7: ex5-7.c
	$(CC) $(CFLAGS) ex5-7.c -o ex5-7 $(LIBS)

q5-1: q5-1.c
	$(CC) $(CFLAGS) q5-1.c -o q5-1 $(LIBS)

q5-2: q5-2.c
	$(CC) $(CFLAGS) q5-2.c -o q5-2 $(LIBS)

q5-3: q5-3.c
	$(CC) $(CFLAGS) q5-3.c -o q5-3 $(LIBS)

q5-4: q5-4.c
	$(CC) $(CFLAGS) q5-4.c -o q5-4 $(LIBS)

q5-5: q5-5.c
	$(CC) $(CFLAGS) q5-5.c -o q5-5 $(LIBS)

clean:
	rm -rf *~  ex5-1 ex5-2 ex5-3 ex5-4 ex5-5 ex5-6 ex5-7 q5-1 q5-2 q5-3 q5-4 q5-5 

