# -------------------------------------
# Makefile; AL2020 (v1.25)             
# (c)2020 The Open University of Japan 
# -------------------------------------

# CC = cc
# CC = clang
CC = gcc
CFLAGS = -Wall -O2
LIBS = -lm

all: ex4-1 ex4-2 

ex4-1: ex4-1.c
	$(CC) ex4-1.c $(CFLAGS) $(LIBS) -o ex4-1

ex4-2: ex4-2.c
	$(CC) ex4-2.c $(CFLAGS) $(LIBS) -o ex4-2

clean:
	rm -rf *~  ex4-1 ex4-2 

